### PR TITLE
Fix last modified script to only change staged files

### LINKED ISSUE #30: last modified script overriding staged changes on each commit
[this line](https://github.com/Upstatement/ups-public-library/blob/eea30877fde830a9c506851f6dcb11971e4c3e5e/scripts/last_modified.sh#L8) changes the pre-commit hook to stage and commit all changes, regardless of what a developer staged prior to committing

### PR DESCRIPTION
**Pull request by bchiang7**
Fixes #30

### CODE REVIEW

File: scripts/last_modified.sh [hunk 1]
```diff
@@ -1,12 +1,14 @@
-git diff --name-only HEAD | while read filename; do
-  if [[ "${filename##*.}" == "md" ]]; then
+# Get staged files
+git diff --name-only --cached HEAD | while read filename; do
```
Comment (bchiang7) [inline scripts/last_modified.sh:2]: `--cached` only shows staged files

File: scripts/last_modified.sh [hunk 2]
```diff
@@ -1,12 +1,14 @@
...
+  # If the file exists and ends in `.md` then update the date field
+  if [[ -f "$filename" && "${filename##*.}" == "md" ]]; then
```
Comment (bchiang7) [inline scripts/last_modified.sh:4]: `[-f "$filename"]` checks if the file exists (in case we delete a `.md` file)

File: scripts/last_modified.sh [hunk 3]
```diff
@@ -1,12 +1,14 @@
...
     last_modified=`date +"%Y-%m-%d"`
     sed -i "" "s|date:.*|date: $last_modified|g" "$filename"
+    echo "Updating timestamp for $filename"
+    git add $filename
```
Comment (bchiang7) [inline scripts/last_modified.sh:8]: Add the individual file
